language: java

matrix:
  include:
    - os: linux
      sudo: required
      group: edge
      services:
        - docker
    - os: osx
      osx_image: xcode8

env:
  global:
    - XGBOOST_VERSION=0.7-20180117153500
    - LIBHDFS_DIR=$HOME/libhdfs-dev
    - HADOOP_VERSION=2.6.0-cdh5.5.0
    - SCALA_VERSION=2.11.0
    - SPARK_VERSION=2.1.1

before_install:
#  - git submodule foreach --recursive git pull origin master
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh travis/install.sh; fi


script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh travis/test_and_package.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        docker run
            -e XGBOOST_VERSION
            -e LIBHDFS_DIR
            -e HADOOP_VERSION
            -e SCALA_VERSION
            -e SPARK_VERSION
            -e TRAVIS_OS_NAME
            -v `pwd`:/xgboost-jars:rw
            centos:centos6
            /bin/bash -c "bash -xe /xgboost-jars/travis/docker.sh";
    fi

cache:
  directories:
    - $LIBHDFS_DIR

deploy:
  provider: releases
  api_key:
    secure: e2k7uYH/Pfi5Wgnd1y7yb57exBSH/Qshy37i04Hnu6ln22Ojgi7lSdYLo+z5EvjmN7iSvw/6t1arEKy2zeUB9JipF7br+FiR4K13FObJV6vYK1w+sQRRNn4N7HsX1mlzvXehvBYf1RjYhEaEQcvfsU+w3kHN1ywoX7beQ+CUGYcxACE2xoO9p2bGuC/dj7gMr/t3IxbbiLjMq6rBJ+sI/Pvfw4mLdfeGf5M/3zuCo8VuBhuHQf0+6OneboHaA3OE2EickMux0CzsQaJLhXh9huBjaybyrTvoz7blIzIAfXqw3w9DwGYeZf9e+CwWDo9wdTiLGW7JTOllTGDs7wHd06fhpWzrrqqJjs+9VTd/9RGMh2pCBE8eywPQGEDCPpASXTdYvJdHBZTyQvHPF+9j5GnQmR2p3vN+XiUdLQFxXsC8DgqlDKPAfulj5su9nnJJnvpJ3HkzoZqxWh4Iz2uTbMzCDMZq1qiYyrZIgQ5RP6Z7fJ10bXPrpoUPM0cLRNz10aOr67XKJeF0q+5FesqXifM6YLiH+RjFxXS7Z0FWE9QIemB/zJ4kvd/1c2uywP3tadN5sWKRxNb71caUVQBM2SIzEZAot2wcGA9OltsAi6AZf6GHv8PmNUU76Oj9Q3z5/A8NYYbhbU/jX6SYDODgLJcdwtY5ffcVl16JasjxRIg=
  file:
    - xgboost4j-$XGBOOST_VERSION-$TRAVIS_OS_NAME.jar
    - xgboost4j-spark-$XGBOOST_VERSION.jar
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
